name: Build and Package Extension

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master ]
  release:
    types: [ published ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [18.x, 20.x]
        browser: [chrome, firefox]
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Run linting
      run: npm run lint || true
      
    - name: Build extension for ${{ matrix.browser }}
      run: npm run build:${{ matrix.browser }}
      
    - name: Upload ${{ matrix.browser }} build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: react-context-devtool-${{ matrix.browser }}-node${{ matrix.node-version }}
        path: |
          dist/${{ matrix.browser }}/
        retention-days: 30
        
    - name: Upload ${{ matrix.browser }} zip package
      uses: actions/upload-artifact@v4
      with:
        name: react-context-devtool-${{ matrix.browser }}-package-node${{ matrix.node-version }}
        path: |
          dist/${{ matrix.browser }}/*.zip
        retention-days: 90

  build-all:
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'release'
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build all browsers
      run: npm run build
      
    - name: Create release packages
      run: |
        mkdir -p release-packages
        cp dist/chrome/*.zip release-packages/
        cp dist/firefox/*.zip release-packages/
        
    - name: Upload release packages
      uses: actions/upload-artifact@v4
      with:
        name: react-context-devtool-release-packages
        path: release-packages/
        retention-days: 365
        
    - name: Upload to release
      if: github.event_name == 'release'
      uses: softprops/action-gh-release@v1
      with:
        files: release-packages/*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  test-build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Test development build
      run: |
        npm run build:dev
        echo "Development build completed successfully"
        
    - name: Verify build outputs
      run: |
        echo "Checking Chrome build..."
        ls -la dist/chrome/ || echo "Chrome dist not found"
        
        echo "Checking Firefox build..."
        ls -la dist/firefox/ || echo "Firefox dist not found"
        
        echo "Checking for zip files..."
        find dist/ -name "*.zip" -exec ls -la {} \; || echo "No zip files found"
        
    - name: Upload test build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: test-build-artifacts
        path: |
          dist/
        retention-days: 7